### ISSUE TITLE
DXF visual problem

### ISSUE THREAD

**Issue by brianwang** [vagran/dxf-viewer#130]
I want to see like this
![Image](https://github.com/user-attachments/assets/638ffdb3-245d-4917-9a70-4b815ec0053e)

but acctually it looks like 

![Image](https://github.com/user-attachments/assets/1b77c713-2d70-4dd6-87c6-b985fb57ee97)

btw, your team did a great job!

thanks for help

[dxf.zip](https://github.com/user-attachments/files/18858444/dxf.zip)

**Comment by vagran** [comment]
Thanks for report!
It is quite strange that you have different result from what I get on the [demo page](https://vagran.github.io/dxf-viewer-example/):

![Image](https://github.com/user-attachments/assets/fcc5a9e2-65cd-4c31-a202-48e848f56967)
Did you try the latest package version?

For arcs, I will try to figure out the problem, probably it is some unimplemented feature, like some kind of splines.

Also, [Autodesk online viewer](https://viewer.autodesk.com) is unable to render this file properly for some reason:

![Image](https://github.com/user-attachments/assets/2297438e-296d-440b-a8b2-0935c76491d9)
I usually use it as reference to verify proper behavior of my viewer. Typically, it is able to properly display any DXF file. It might happen, that your software produce something which is not compliant with the generic DXF specification.

**Comment by brianwang** [comment]
Thanks for help. I've updated to the latest version 1.0.40, but it still not working.  We will wait for the laest update.

**Comment by vagran** [comment]
Arcs fixed in `1.0.41`.

![Image](https://github.com/user-attachments/assets/898d09b4-96fe-44be-a634-3a225fc22263)

There are still some unimplemented features, specifically line patterns and line with physical width specified. Now they are rendered just as a continuous single-pixel wide line.

**Comment by brianwang** [comment]
Great job!!!

I still have another enhancement.

![Image](https://github.com/user-attachments/assets/4595faff-de9b-4f4e-a053-01293608da5e)

But version 1.0.41 

![Image](https://github.com/user-attachments/assets/3c1c7e27-90c5-4d6c-88d4-f131aa4cd2c6)

Maybe it is another missing component of need to implement function. 

Thanks again

[dxf.zip](https://github.com/user-attachments/files/18935566/dxf.zip)
